language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: h4oA2T0qUMaAPkoUtseYKuU6QCtXXBEBqRRl/78ILBRM8kP2Ivj6dkbGfGNV0/6qV9AkzMBm8lciE95InkpTdWLf4SIBkjALoKPru4lZGcHGHdybNuBbDjlHpzYuR0OAll/Ox9jDUqnQDoM6SMbxtknxjyW9w0sJvFYbi9mB2bmQ5buI4oo8tXva/LtE7wRo1Q64b5JTU8wEf6FphgGnIMyXrxhGCQTUY1/Aasiy0MCusng6UpszBFso/KyRZQpVqhVAL7SaRf0C0JNsIByHsY84R1V5pktG/V8R7aJRqI+xc0SQw2QypS4NTH2Vus5zk2jGoAZCdV0/7MVmwBTkQsJwjb2LSQaEE+Zv2ShTyyaG7CpWHDbLKj0ZGlIOdRg39VOwZH+rd4/lSQ6vBOXT6cdhCfTlJ+mtS+aSBQJPck8DS/vPak0S211KYfAQDexthbY+d476jfHvOSbvN/rDulNKSTtgHU2+ouwnUo6T65Ujw1BiAqaIaFk4Vzr7iQlGbxiZshmKEeaZiSRA61WqDukKPmWwdqL63lR8QPrRivSFCOyGDCr0/ihEjBtWM4j3MD+HYAFxZlvG7ale6noU9/JkdR7YCAZ1VG+78hhFna/zTK1VkUC4QL9OXihq+E1pOR9oEI1ib3MthoxEdd3o8IlysEe+p1hRXK7WidxiYKk=
  app: Cameron-API
  on:
    repo: amyspeed/Cameron-API
  skip_cleanup: 'true'
